#!/bin/sh -x
# Copyright © 2009-2011 by Cycojesus

MAKE_DEPS=${MAKE_DEPS:-YES}

GEM=${GEM:-$1}

ARCH=${ARCH:-noarch}
BUILD=${BUILD:-1}
TAG=${TAG:-$(basename $0)}
OUTPUT=${OUTPUT:-/tmp}
TMP=${TMP:-/tmp/$TAG}
PKG=${PKG:-$TMP/pkg-rubygem-$GEM}
PREFIX=${PREFIX:-/usr}

GEMSROOT=${GEMSROOT:-$(gem environment gemdir)}

if [ $MAKE_DEPS == YES ]; then
    for i in $(gem dependency --pipe --remote $* | cut -d\  -f1); do
        $0 $i
    done
fi

rm -fr $PKG

mkdir -p $PKG$GEMSROOT

gem install $* \
    --install-dir $PKG$GEMSROOT \
    --bindir $PKG$PREFIX/bin \
    --force \
    --ignore-dependencies

cd $PKG

PRGNAM=rubygem-$(grep "s\.name = " $PKG$GEMSROOT/specifications/*.gemspec | grep -o "%q{.*}" | sed 's|%q{||' | tr -d '}')
VERSION=$(grep "s\.version = " $PKG$GEMSROOT/specifications/*.gemspec | grep -o "\".*\"" | tr -d '"')

mkdir -p $PKG/install
cat <<EOF > $PKG/install/slack-desc
$PRGNAM: $PRGNAM ($(grep "s\.summary = " $PKG$GEMSROOT/specifications/*.gemspec | grep -o "%q{.*}" | sed 's|%q{||' | tr -d '}'))
$PRGNAM:
$PRGNAM: $(grep "s\.description = " $PKG$GEMSROOT/specifications/*.gemspec | grep -o "%q{.*}" | sed 's|%q{||' | tr -d '}')
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM:
$PRGNAM: $(grep "s\.homepage = " $PKG$GEMSROOT/specifications/*.gemspec | grep -o "%q{.*}" | sed 's|%q{||' | tr -d '}')
$PRGNAM:
EOF

chown -R rooot:root .

makepkg --linkadd y --chown n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
